//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioVozDelEste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public int ComentarioID { get; set; }
        public string Comentario { get; set; }
        public System.DateTime Fecha { get; set; }
        public string ClienteID { get; set; }
        public int ProgramaID { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Programas Programas { get; set; }
    }
}
